FROM jenkinsci/jenkins:2.7

USER root

# install cf cli
ENV CF_CLI $PWD/
ENV PATH $CF_CLI:$PATH
ADD https://cli.run.pivotal.io/stable?release=linux32-binary&version=6.19.0&source=github-rel $CF_CLI/cf.tgz
RUN tar zxvf $CF_CLI/cf.tgz && cf --version

WORKDIR /tmp/files
RUN chown -R jenkins.jenkins .

USER jenkins

COPY plugins.txt .
RUN mkdir -p /usr/share/jenkins/ref && /usr/local/bin/plugins.sh plugins.txt

ADD JENKINS_HOME /usr/share/jenkins/ref

USER root
RUN chown -R jenkins.jenkins /usr/share/jenkins/ref
COPY run.sh /usr/local/bin/
RUN chmod a+x /usr/local/bin/run.sh

USER jenkins
CMD /usr/local/bin/run.sh

EXPOSE 8080
